### ISSUE TITLE
Reverting to default

### ISSUE THREAD

**Issue by caiofaustino** [raelgc/win_us_intl#11]
Excuse my lack of knowledge in this, but I wanted to install this to see how it behaves, but I'm concerned on how to revert the changes.

Can you just confirm a few things?
- I can revert the `im-config -n uim` with `im-config -n ibus` right?
- What does `gsettings set org.gnome.settings-daemon.plugins.xsettings disabled-gtk-modules '["'keyboard'"]'` do? 
How do I revert it back if I need?

I'm running Pop!_OS so it's basically Ubuntu afaik. Sorry for the noob questions, I just like to understand things a bit better before I try to change them.

**Comment by raelgc** [comment]
Hi @caiofaustino,

Indeed, we're missing a revert section. I'll add it.

About your questions:
- yes, `ibus` is the default 
- Revert the second command with `gsettings set org.gnome.settings-daemon.plugins.xsettings disabled-gtk-modules '[]'`

**Comment by caiofaustino** [comment]
Thanks a lot!
