### ISSUE TITLE
Pop!_OS | Repository does not have release file

### ISSUE THREAD

**Issue by VFViotti** [raelgc/win_us_intl#14]
Good evening. I've tried adding your repository to my repository list but there was some issues. I'm adding the log below for reference. I'm also bolding the two line with issues that I located:

~$ sudo apt-add-repository -y ppa:rael-gc/utils
Repository: 'deb http://ppa.launchpad.net/rael-gc/utils/ubuntu/ hirsute main'
Description:
Useful stuff like:
- package to configure US-international keyboard like MS Windows(TM)
- xf86-input-xwiimote updated for HWE.
More info: https://launchpad.net/~rael-gc/+archive/ubuntu/utils
Adding repository.
Adding deb entry to /etc/apt/sources.list.d/rael-gc-ubuntu-utils-hirsute.list
Adding disabled deb-src entry to /etc/apt/sources.list.d/rael-gc-ubuntu-utils-hirsute.list
Adding key to /etc/apt/trusted.gpg.d/rael-gc-ubuntu-utils.gpg with fingerprint 7BE3E5681146FD4F1A40EDA28094BB14F4E3FBBE
Hit:1 http://dl.google.com/linux/earth/deb stable InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu hirsute InRelease                                                             
Hit:3 https://download.cudo.org/repo/apt stable InRelease                                                               
Hit:4 http://us.archive.ubuntu.com/ubuntu hirsute-security InRelease                                                    
Hit:5 http://ppa.launchpad.net/system76/pop/ubuntu hirsute InRelease                                                    
Hit:6 http://apt.pop-os.org/proprietary hirsute InRelease                                                               
Hit:7 http://us.archive.ubuntu.com/ubuntu hirsute-updates InRelease                                                     
Hit:8 https://dl.winehq.org/wine-builds/ubuntu groovy InRelease                                                      
Hit:9 http://us.archive.ubuntu.com/ubuntu hirsute-backports InRelease                                                
Hit:10 https://repo.protonvpn.com/debian stable InRelease                                      
Ign:11 http://ppa.launchpad.net/rael-gc/utils/ubuntu hirsute InRelease
Err:12 http://ppa.launchpad.net/rael-gc/utils/ubuntu hirsute Release
  **404  Not Found [IP: 91.189.95.85 80]**
Reading package lists... Done                      
**E: The repository 'http://ppa.launchpad.net/rael-gc/utils/ubuntu hirsute Release' does not have a Release file.**
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by raelgc** [comment]
Hi @Vviotti and thanks for raising this issue. Indeed, I forgot to publish for new Ubuntu release. It's published now. Can you, please, try again?

**Comment by VFViotti** [comment]
Worked like a charm. It is still not working, with the us int with dead keys, but I'll work my way over the troubleshoot.
