### ISSUE TITLE
Segfault on `ibus` daemon causing huge input lag on Ubuntu 18

### ISSUE THREAD

**Issue by enricodias** [raelgc/win_us_intl#18]
After installing and rebooting, the whole system had a huge input lag on both the mouse and keyboard. Syslog shows multiple segfault errors when starting the ibus-daemon.

I tried the normal install and it didn't work. Then I tried the manual install and the issue occurred. Apparently the .XCompose file has an error, because removing that file solved the ibus error.

The solution overall still doesn't work. I'm with all env vars set, int keyboard with dead keys, .XCompose loaded and I still need to press space to write simple quotes.

**Comment by raelgc** [comment]
Hi @enricodias and sorry to hear about that.

There is a huge time since I don't use Ubuntu 18 (I switched to 20 after its release, and now I'm under 22).

In theory, this solution doesn't rely on `ibus`, but on `uim` as input method.

Are you using default Unity or any other desktop environment?

To revert to iUbs, after remove the package (or manually the local `.XCompose` file), you can revert to iBus running `im-config -n ibus`

**Comment by enricodias** [comment]
I'm using gnome. Removing the `.XCompose` file from the home folder stops ibus from failing (the one created by the manual install). The `.XCompose` installed by the package doesn't cause the issue, but doesn't work.

And I can see that it's loaded:
```
strace -e open,openat xterm |& grep Compose                        
openat(AT_FDCWD, "/home/USER/.XCompose", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/share/X11/locale/en_US.UTF-8/Compose", O_RDONLY) = 15
openat(AT_FDCWD, "/usr/share/X11/locale/en_US.UTF-8/Compose.diverted-win-us-intl", O_RDONLY) = 16
```

Also, my cedilha was working before trying this and now it's not. I have no idea why.

**Comment by raelgc** [comment]
Try restore the system `XCompose` with:

```
sudo mv /usr/share/X11/locale/en_US.UTF-8/Compose /usr/share/X11/locale/en_US.UTF-8/Compose.bak
sudo apt-get -f install
```

**Comment by enricodias** [comment]
I cleaned everything, reinstalled the package and `ibus`, rebooted and managed to get it working. Using the manual install still results in segfaults with the `ibus` daemon, tho. The system tries to restart it constantly and the result is a huge input lag. Initially it just feels like the computer is really slow, but everything runs smoothly and just the inputs that take seconds to compute. I'm not sure what's the cause, the system gets too laggy to debug. The faults are shown in the syslog only.

I'll close this and update the title just to make it easier to find in case someone else has the same issue.

**Comment by raelgc** [comment]
I'm glad you solved and got your system working again! :)
