### ISSUE TITLE
creating ~/.XCompose is enough?

### ISSUE THREAD

**Issue by perroboc** [raelgc/win_us_intl#19]
Hi! this is not much of an issue as it is just a question... I just did this:

`wget https://raw.githubusercontent.com/raelgc/win_us_intl/master/.XCompose ~/.XCompose`

then logged out, and that's it... using Pop!_OS 22.04 LTS

is this enough?

**Comment by raelgc** [comment]
If `ibus` is now supporting the `.XCompose` file and you want to change only your user, then yes :)

**Comment by perroboc** [comment]
Awesome! And yeah, only user here. Thanks!
