### ISSUE TITLE
Installation no longer works in newer version of GNOME

### ISSUE THREAD

**Issue by lmedinado** [raelgc/win_us_intl#2]
The command 
`gsettings set org.gnome.settings-daemon.plugins.keyboard active false`
no longer works at least as of Fedora 27. What worked was
`gsettings set org.gnome.settings-daemon.plugins.xsettings disabled-gtk-modules '["'keyboard'"]'`

I also couldn't get `uim` to run properly under Wayland. I don't know where the bug is, but I would advise anyone having trouble with this to stick to Xorg for the time being.

**Comment by raelgc** [comment]
Thank you @lmedinado for all these infos!
