### ISSUE TITLE
Issue of ç on firefox and chrome - possible issue due to snap and flatpak packages

### ISSUE THREAD

**Issue by asheshstha** [raelgc/win_us_intl#21]
I am facing issues with `ç` key on some softwares.

Setup 
- Ubuntu 22.04
- Keyboard - US intl with dead keys

Software list:
|Software|Type|Issue|
|-|-|-|
|Firefox|snap|yes|
|Firefox Dev Edition|deb|no|
|Chrome|flatpak|yes|
|calc|Ubuntu default|no|
|terminal|Ubuntu default|no|
|Ubuntu search| Ubuntu default|yes|
|obsidian¹|flatpak|yes|

I am not sure where the issue is but I found similar issue at: https://bugs.launchpad.net/ubuntu/+source/firefox/+bug/1946769

## Edits:
Edit¹: obsidian - flatpack - has issue. Changed form no to yes.

**Comment by raelgc** [comment]
@asheshstha Thanks for reporting this, it's very interesting.

I can see that sandboxed format software (flatpack, snap) is ignoring the user input method (we're using `uim` as the input method instead of the default `ibus`, which ignores the `XCompose` file).

So, we need to investigate why flatpack and snap are ignoring other than `ibus`.

For the Ubuntu default search, the only issue I can see happens if `ç` is the first letter: it works if not the first. Is the same happening for you?

**Comment by asheshstha** [comment]
@raelgc 
For ubuntu search, the issue (`Ć` instead of `ç`) persists even for other than first characters. But I am not much worried about search issue because other ubuntu pre-installed apps such as calculator, terminal, libre office works well.

But I guess for all flatpak and snaps, we have issue. Is there anything that I do to help?

**Comment by raelgc** [comment]
One idea would be try the current `ibus` included in Ubuntu: I just tested and it appears to work with our `.XCompose` file. 

But even on this case, maybe flatpak/snap will ignore the user local `.XCompose`. I don't know if `ibus` supports a global (system wide) Compose file.

If you're willed to try (and assuming you installed the Ubuntu package), you can select `ibus` using:

    im-config -n ibus
    gsettings set org.gnome.settings-daemon.plugins.xsettings disabled-gtk-modules '[]'

Then download the `.XCompose` file to your home folder:

    cd
    wget https://raw.githubusercontent.com/raelgc/win_us_intl/master/.XCompose

Probably you'll need to logout and login again. Then test with flatpak/snap apps.

**Comment by asheshstha** [comment]
@raelgc yes your solution fixed the issue. The issue has been fixed on all platforms - ubuntu search, flatpak, and snap packages when tested on Ubuntu 22.04

**Comment by raelgc** [comment]
Thanks for your time testing and the feedback, @asheshstha. I've updated the README file to instruct people to first just try to download the `.XCompose` file.
