### ISSUE TITLE
Pressing two times ` (dead_grave/grave) is still producing a single grave

### ISSUE THREAD

**Issue by GabeDuarteM** [raelgc/win_us_intl#22]
Hey! Thank you for the handy compose file, It has been working wonders for most of the accents I was used to, but I noticed one of them is still a bit wonky, which is when I want to produce multiple \` in sequence (used a lot for coding, for example), if I press two times the character \`, it still gives me a single \` instead of \`\` which is what I would expect

Any idea why that's the case? I inspected the .XCompose file and it seems like the line is there, but for some reason, it's not being respected...
![image](https://github.com/raelgc/win_us_intl/assets/7675500/b3d057e6-d3f6-4aba-b4ab-4edab278c3bb)

I'm using Fedora 38 (Nobara Linux 38) and the keyboard is `English (US, intl., with dead keys)`, and to "install" this I just dropped the .XCompose file downloaded from here into my home folder and rebooted

**Comment by raelgc** [comment]
Sounds like a `uim` issue.

You can try with `ibus` + the `.XCompose` file. Or even installing `en-us ISO-8859-1` locale.

With updated `ibus`, I think the `uim` solution is no more required. Probably I'll not release this package for next Ubuntu.

**Comment by GabeDuarteM** [comment]
@raelgc Hmmm, I don't have `uim` installed, so I imagine fedora is using ibus automatically for that already?

I "installed" this just by placing the .XCompose file on the home folder and it picked up most things flawlessly, the only one missing is the \`, as I mentioned here

My ibus version is 1.5.28, which is the most up to date on the fedora repo

I also tried updating the locales to use `en_US ISO-8859-1`, but the only thing that changed was messing up my terminal fonts, but the accents continue the same as they were before...
![image](https://github.com/raelgc/win_us_intl/assets/7675500/bafc41c0-3bb6-4c1f-9063-3f5df588a06d)

Also, not sure if Fedora comes with it by default, but I've always used UTF-8, not sure what changes with ISO-8859-1 in this case

**Comment by raelgc** [comment]
So probably you'll need to open an `ibus` issue.

**Comment by raelgc** [comment]
One side note: if you're trying the `8859-1` locale, you can try rename the `.XCompose` file and restart.
