### ISSUE TITLE
It is not working in Ubuntu 18.04

### ISSUE THREAD

**Issue by decarvalhorobinson** [raelgc/win_us_intl#3]
Tried to make it work in Ubuntu Bionic Beaver, even installing something it is not activating the keyboard

**Comment by raelgc** [comment]
Oh God, I still has not installed 18.04 to test. Hope I'll be able to install during the next weekend.

**Comment by raelgc** [comment]
Hi @decarvalhorobinson. I just installed 18.04 and realized it was missing a package in Launchpad. I just fixed and now it's working. Please, update and upgrade.
