### ISSUE TITLE
.deb installation is not working on xubuntu 18.04 LTS

### ISSUE THREAD

**Issue by yoisel** [raelgc/win_us_intl#4]
I was using 16.04 where the binary .deb file worked fine.
I did a clean install of 18.04, tried to install the .deb file and it fails with the following error:

dpkg-divert: error: rename involves overwriting '/usr/share/X11/locale/en_US.UTF-8/Compose' with
  different file '/usr/share/X11/locale/en_US.UTF-8/Compose.diverted-win-us-intl', not allowed
dpkg: warning: old win-us-intl package post-removal script subprocess returned error exit status 2
dpkg: trying script from the new package instead ...
Removing 'diversion of /usr/share/X11/locale/en_US.UTF-8/Compose to /usr/share/X11/locale/en_US.UTF-8/Compose.diverted-win-us-intl by win-us-intl'
dpkg-divert: error: rename involves overwriting '/usr/share/X11/locale/en_US.UTF-8/Compose' with
  different file '/usr/share/X11/locale/en_US.UTF-8/Compose.diverted-win-us-intl', not allowed
dpkg: error processing archive /home/someuser/Downloads/win-us-intl_20140423-1_all.deb (--install):
 new win-us-intl package post-removal script subprocess returned error exit status 2
Removing 'diversion of /usr/share/X11/locale/en_US.UTF-8/Compose to /usr/share/X11/locale/en_US.UTF-8/Compose.diverted-win-us-intl by win-us-intl'
dpkg-divert: error: rename involves overwriting '/usr/share/X11/locale/en_US.UTF-8/Compose' with
  different file '/usr/share/X11/locale/en_US.UTF-8/Compose.diverted-win-us-intl', not allowed
dpkg: error while cleaning up:
 new win-us-intl package post-removal script subprocess returned error exit status 2
Errors were encountered while processing:
 /home/someuser/Downloads/win-us-intl_20140423-1_all.deb

**Comment by raelgc** [comment]
Had you tried the 18.04 version available in https://launchpad.net/~rael-gc/+archive/ubuntu/utils/+packages ?

**Comment by yoisel** [comment]
Oh did not know about that one. thanks.

**Comment by yoisel** [comment]
The ppa version works fine. Thanks again.

**Comment by raelgc** [comment]
You're welcome!
