### ISSUE TITLE
is the ppa updated for ubuntu 20.04?

### ISSUE THREAD

**Issue by ericoporto** [raelgc/win_us_intl#7]
is this working on Ubuntu 20.04? This is mentioned as a possible solution in IntelliJ bugtracker : https://youtrack.jetbrains.com/issue/IDEA-59679

**Comment by raelgc** [comment]
Hi @ericoporto! I'm still using 18.04. I'm planning to upgrade this weekend, so I can give you a better answer.

**Comment by raelgc** [comment]
@ericoporto All fine in 20.04? I just started using these days, and aside had to disable the bottom right indicator, it appears to be working fine.
